# Generated by Django 5.1.2 on 2024-10-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cake_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('baby_shower', 'Baby Shower'), ('gender_reveal', 'Gender Reveal'), ('Communion', 'Communion'), ('Confirmation', 'Confirmation'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
