# Generated by Django 5.1.2 on 2024-11-06 22:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cake_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
